"""
Django settings for questov1 project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ID = 1
SITE_BUIDS = []

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pdota(rl+4#lnmlt=oolu1tbgp=py-4aldzzd&c)0&m+73y_k^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = '/login/'   #<-- add
LOGIN_REDIRECT_URL = '/profile/view/'

AUTHENTICATION_BACKENDS = (
    'backends.CaseInsensitiveAuthBackend',
    'django.contrib.auth.backends.ModelBackend',  # default
    'django.contrib.auth.backends.RemoteUserBackend',  # http
)

# Application definition

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.sitemaps',
    'django.contrib.flatpages',
    'django.contrib.redirects',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_extensions',
    'usermodel',
    'myprofile',
    'registrations',
#    'mysignon',
#    'mydashboard',
#    'solr',
#    'mysearches',
#    'mypartners',
#    'seo',
#    'myreports',
#    'mymessages',
#    'myemails',
#    'postajob',
#    'redirect',
)
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'questov1.urls'


TEMPLATE_DIRS = [
    os.path.join(BASE_DIR,"templates"),
    ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': (os.path.join(BASE_DIR, 'templates'),),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'questov1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



GRAVATAR_URL_PREFIX = "https://secure.gravatar.com/avatar/"
GRAVATAR_URL_DEFAULT = 404

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'usermodel.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

if DEBUG:
    MEDIA_URL = '/media/'
    STATIC_ROOT = os.path.join(BASE_DIR, "static","static_root")
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR,"static","static_dirs"),
        )

# email types
ACTIVATION = 1
CREATE_CONTACT_RECORD = 3
FORGOTTEN_PASSWORD = 4
GENERIC = 5
INACTIVITY = 6
INVITATION = 7
INVOICE = 8
PARTNER_SAVED_SEARCH_RECIPIENT_OPTED_OUT = 10
POSTING_REQUEST_CREATED = 11
SAVED_SEARCH = 12
SAVED_SEARCH_DIGEST = 13
SAVED_SEARCH_DISABLED = 14
SAVED_SEARCH_INITIAL = 15
SAVED_SEARCH_UPDATED = 16


FORM_DATE_FORMAT = '%m/%d/%Y'

DATE_INPUT_FORMATS = (
    '%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y',
    '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y',
    '%d %B, %Y',
)


DATE_INPUT_FORMATS += (FORM_DATE_FORMAT,)

PROFILE_COMPLETION_MODULES = (
    'basicinfo',
    'experience',
    'skill',
    'education',
    'social',
)

import mimetypes
mimetypes.add_type("image/svg+xml", ".svg", True)
mimetypes.add_type("image/svg+xml", ".svgz", True)
